[package]
name = "syscall_loop"
version = "0.0.0"
authors = ["Guillaume Bertholon <guillaume.bertholon@ens.fr>",
           "Nicolas Chataing <nicolas.chataing@ens.fr>"]

[lib]
crate-type = ["staticlib"]
path = "main.rs"

[dependencies]
rustberry_std = { path = "../../libstd" }
