[package]
name = "rustberry"
version = "0.0.0"
authors = ["Guillaume Bertholon <guillaume.bertholon@ens.fr>",
           "Nicolas Chataing <nicolas.chataing@ens.fr>"]

[lib]
crate-type = ["staticlib"]
path = "src/kernel.rs"

[dependencies]
rlibc = "1.0"

[features]
raspi1 = []
raspi2 = []
