[package]
name = "hello_world"
version = "0.0.0"
authors = ["Guillaume Bertholon <guillaume.bertholon@ens.fr>"]

[lib]
crate-type = ["staticlib"]
path = "main.rs"

[dependencies]
rustberry_io = { path = "../../io" }
rustberry_std = { path = "../../std" }
