[package]
name = "rustberry_io"
version = "0.0.0"
authors = ["The Rust Project Developers",
           "Stripped down by Guillaume Bertholon"]
edition = "2018"

[lib]
crate-type = ["rlib"]
path = "lib.rs"
