[package]
name = "memory_monster"
version = "0.0.0"
authors = ["Guillaume Bertholon <guillaume.bertholon@ens.fr>"]

[lib]
crate-type = ["staticlib"]
path = "main.rs"

[dependencies]
rustberry_std = { path = "../../libstd" }
